IntegrationProject/IntegrationProject/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace IntegrationProject.Models
{
    public class User
    {
        [Key]
        public int ID { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [RegularExpression(@"\d{10}$", ErrorMessage = "Invalid Phone Number")]
        public string Phone { get; set; }

        public string Description { get; set; }

        [Display (Name = "Up Vote")]
        public int VolunteerUpVotes { get; set; }

        [Display(Name = "Down Vote")]
        public int VolunteerDownVotes { get; set; }

        [Display(Name = "Up Vote")]
        public int EventUpVotes { get; set; }

        [Display(Name = "Down Vote")]
        public int EventDownVotes { get; set; }

        [Display(Name = "No Show")]
        public int NoShowCount { get; set; }

        
    }
}

IntegrationProject/IntegrationProject/Controllers/VolunteerEventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IntegrationProject.Models;
using Microsoft.AspNet.Identity;

namespace IntegrationProject.Controllers
{
    public class VolunteerEventsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: VolunteerEvents
        public ActionResult Index(string searchString)
        {
            ViewBag.LoggedUser = User.Identity.GetUserId();

            var events = from m in db.VolunteerEvent
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                events = events.Where(s => s.Address.Contains(searchString));
            }

            return View(events);
        }

        public ActionResult IndexMyEvents()
        {
            var loggedUserID = User.Identity.GetUserId();
            var loggedUser = User.Identity.GetUserName();
            var users = db.User.Single(v => v.Email == loggedUser);

            var events =
                from u in db.User_Event
                join e in db.VolunteerEvent on u.VolunteerEventID equals e.ID
                join v in db.User on u.UserID equals v.ID
                where u.UserID == users.ID
                select e;

            ViewBag.LoggedUserID = loggedUserID;
            return View(events);
        }

        // GET: VolunteerEvents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            VolunteerEvent volunteerEvent = db.VolunteerEvent.Find(id);
            var host = (from a in db.Users
                        join e in db.VolunteerEvent on a.Id equals e.HostID
                        join v in db.User on a.UserID equals v.ID
                        where e.ID == id && e.HostID == a.Id && a.UserID == v.ID
                        select new
                        {
                            FirstName = v.FirstName,
                            LastName = v.LastName,
                            HostID = e.HostID,
                            EndDate = e.EndDate
                        });

            foreach (var x in host)
            {
                ViewBag.First = x.FirstName;
                ViewBag.Last = x.LastName;
                ViewBag.Host = x.HostID;
                ViewBag.EndDate = x.EndDate;
            }

            ViewBag.LoggedUser = User.Identity.GetUserId();

            var loggedUser = User.Identity.GetUserName();
            var users = db.User.Single(v => v.Email == loggedUser);

            var userEvents =
                from u in db.User_Event
                join e in db.VolunteerEvent on u.VolunteerEventID equals e.ID
                join v in db.User on u.UserID equals v.ID
                where u.UserID == users.ID && u.VolunteerEventID == id
                select v;

            if(!userEvents.Any())
            {
                ViewBag.Volunteer = "false";
            }

            if (volunteerEvent == null)
            {
                return HttpNotFound();
            }
            return View(volunteerEvent);
        }

        // GET: VolunteerEvents/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VolunteerEvents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VolunteerEvent volunteerEvent)
        {
            var loggedUser = User.Identity.GetUserName();
            var users = db.User.Single(v => v.Email == loggedUser);

            volunteerEvent.HostID = User.Identity.GetUserId();

            User_Event user_event = new User_Event
            {
                UserID = users.ID,
                VolunteerEventID = volunteerEvent.ID
            };

            if (ModelState.IsValid)
            {
                db.User_Event.Add(user_event);
                db.VolunteerEvent.Add(volunteerEvent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(volunteerEvent);
        }

        // GET: VolunteerEvents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VolunteerEvent volunteerEvent = db.VolunteerEvent.Find(id);
            if (volunteerEvent == null)
            {
                return HttpNotFound();
            }
            return View(volunteerEvent);
        }

        // POST: VolunteerEvents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit(VolunteerEvent volunteerEvent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(volunteerEvent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("SendMail", "Home", volunteerEvent);
            }
            return View(volunteerEvent);
        }

        // GET: VolunteerEvents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VolunteerEvent volunteerEvent = db.VolunteerEvent.Find(id);
            if (volunteerEvent == null)
            {
                return HttpNotFound();
            }
            return View(volunteerEvent);
        }

        // POST: VolunteerEvents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            VolunteerEvent volunteerEvent = db.VolunteerEvent.Find(id);
            db.VolunteerEvent.Remove(volunteerEvent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult IndexVolunteerRoute(int id)
        {
            //return View();
            return RedirectToAction("IndexEventVolunteers", "Users", new { id = id });
        }

        public ActionResult IndexVolunteerRouteViewOnly(int id)
        {
            //return View();
            return RedirectToAction("IndexEventVolunteersViewOnly", "Users", new { id = id });
        }

        public ActionResult IndexHostRoute(int id)
        {
            //return View();
            return RedirectToAction("IndexEventHost", "Users", new { id = id });
        }

        public ActionResult AddUserToEvent(int id)
        {
            var loggedUser = User.Identity.GetUserName();
            var users = db.User.Single(v => v.Email == loggedUser);

            User_Event user_event = new User_Event
            {
                UserID = users.ID,
                VolunteerEventID = id
            };

            db.User_Event.Add(user_event);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult CancelVolunteerEvent(int id)
        {
            var loggedUser = User.Identity.GetUserName();
            var users = db.User.Single(v => v.Email == loggedUser);

            var userEvent = db.User_Event.Single(e => e.VolunteerEventID == id && e.UserID == users.ID);
           
            User_Event user_event = db.User_Event.Find(userEvent.ID);
            db.User_Event.Remove(userEvent);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

IntegrationProject/IntegrationProject/Views/Users/Calendar.cshtml
@model IntegrationProject.Models.User

@{
    ViewBag.Title = "Calendar";
    //Layout = "~/Views/Shared/_LayoutVolunteer.cshtml";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <link href="~/Content/fullcalendar.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/fullcalendar.js"></script>

    <script>
        $(document).ready(function () {

            // page is now ready, initialize the calendar...

            $('#calendar').fullCalendar({
                // put your options and callbacks here
            })
                //< a href= "~/Controllers/UsersController.cs" > ~/Controllers/UsersController.cs</a >
            var eventsArray = [];

            //for (var i = 1; i < 32; i++) {
            //    var sampleEvent = {
            //        "id": "2302",
            //        "title": "New Event",
            //        "start": "8/" + i.toString() + "/2017 12:00:00 AM",
            //        "end": "8/" + i.toString() + "/2017 12:00:00 PM",
            //        "allDay": true,
            //        "url": "https://www.google.com"
            //    }
            //    eventsArray.push(sampleEvent);
            //}

            @*var titleString = (@ViewBag.Json).toString();*@
            var titleString = "Event";

            var sampleEvent = [{
                    "id": "2302",
                    "title": titleString,
                    "start": "8/5/2017 12:00:00 AM",
                    "end": "8/9/2017 12:00:00 PM",
                    "allDay": false,
                    "url": "https://www.google.com"
                }]

            @*var actionUrl = '@Url.Action("GetEvents", "UsersController")';
            eventsArray.push($.getJSON(actionUrl));*@

            @*var eventData = (@ViewBag.Json);*@

            $('#calendar').fullCalendar('addEventSource', sampleEvent);
        });
    </script>

</head>

<h2 style="color:red">Calendar</h2>

<div id="calendar"></div>

IntegrationProject/IntegrationProject/Views/Users/Create.cshtml
@model IntegrationProject.Models.User

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutVolunteer.cshtml";
}

<h2>Create Volunteer Profile</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IntegrationProject/IntegrationProject/Views/Users/Delete.cshtml
@model IntegrationProject.Models.User

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.VolunteerUpVotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VolunteerUpVotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VolunteerDownVotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VolunteerDownVotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventUpVotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventUpVotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDownVotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDownVotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoShowCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoShowCount)
        </dd>*@

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "UserSignedInIndex")
        </div>
    }
</div>

IntegrationProject/IntegrationProject/Views/Users/Details.cshtml
@model IntegrationProject.Models.User

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutVolunteer.cshtml";
}

<h2>Details</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VolunteerUpVotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VolunteerUpVotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VolunteerDownVotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VolunteerDownVotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventUpVotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventUpVotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDownVotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDownVotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoShowCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoShowCount)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "UserSignedInIndex")
</p>

IntegrationProject/IntegrationProject/Views/Users/Edit.cshtml
@model IntegrationProject.Models.User

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutVolunteer.cshtml";
}

<h2>Edit Profile</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>User</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "UserSignedInIndex")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IntegrationProject/IntegrationProject/Views/Users/IndexEventHost.cshtml
@model IEnumerable<IntegrationProject.Models.User>

@{
    ViewBag.Title = "IndexEventHost";
    Layout = "~/Views/Shared/_LayoutVolunteer.cshtml";
}
<h2>Event Host</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventUpVotes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventDownVotes)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.FirstName, "ReadOnlyIndex", new { id = item.ID }, new { target = "_blank" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                <a href="@Url.Action("EventUpVotesCounter", new { id = item.ID, eventId = ViewBag.HostEventId })">
                    <img src="@Url.Content("~/Images/thumbsup.png")" alt="Thumbs Up" width="30" height="30" />
                </a>
                @Html.DisplayFor(modelItem => item.EventUpVotes)
            </td>
            <td>
                <a href="@Url.Action("EventDownVotesCounter", new { id = item.ID, eventId = ViewBag.HostEventId })">
                    <img src="@Url.Content("~/Images/thumbsdown.png")" alt="Thumbs Down" width="30" height="30" />
                </a> 
                @Html.DisplayFor(modelItem => item.EventDownVotes)
            </td>
            @*
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID })
                </td>*@            
        </tr>
    }

    <tr>
        <td>
            @Html.ActionLink("Back", "Index", "VolunteerEvents")
        </td>
    </tr>

</table>



IntegrationProject/IntegrationProject/Views/Users/IndexEventVolunteers.cshtml
@model IEnumerable<IntegrationProject.Models.User>

@{
    ViewBag.Title = "IndexEventVolunteers";
    Layout = "~/Views/Shared/_LayoutVolunteer.cshtml";
}
<h2>Event Volunteers</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VolunteerUpVotes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VolunteerDownVotes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoShowCount)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.FirstName, "ReadOnlyIndex", new { id = item.ID }, new { target = "_blank" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                <a href="@Url.Action("VolunteerUpVotesCounter", new { id = item.ID, eventId = ViewBag.VolunteerEventId })">
                    <img src="@Url.Content("~/Images/thumbsup.png")" alt="Thumbs Up" width="30" height="30" />
                </a>
                @Html.DisplayFor(modelItem => item.VolunteerUpVotes)
            </td>
            <td>
                <a href="@Url.Action("VolunteerDownVotesCounter", new { id = item.ID, eventId = ViewBag.VolunteerEventId })">
                    <img src="@Url.Content("~/Images/thumbsdown.png")" alt="Thumbs Down" width="30" height="30" />
                </a> 
                @Html.DisplayFor(modelItem => item.VolunteerDownVotes)
            </td>
            <td>
                <a href="@Url.Action("NoShowVotesCounter", new { id = item.ID, eventId = ViewBag.VolunteerEventId  })">
                    <img src="@Url.Content("~/Images/noshow.jpg")" alt="No Show" width="30" height="30" />
                </a>
                @Html.DisplayFor(modelItem => item.NoShowCount)
            </td>
            @*
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID })
                </td>*@            
        </tr>
    }

    <tr>
        <td>
            @Html.ActionLink("Back", "Index", "VolunteerEvents")
        </td>
    </tr>

</table>



IntegrationProject/IntegrationProject/Views/Users/IndexEventVolunteersViewOnly.cshtml
@model IEnumerable<IntegrationProject.Models.User>

@{
    ViewBag.Title = "IndexEventVolunteersViewOnly";
}
<h2>Event Volunteers</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VolunteerUpVotes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VolunteerDownVotes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoShowCount)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.FirstName, "ReadOnlyIndex", new { id = item.ID }, new { target = "_blank" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                <img src="@Url.Content("~/Images/thumbsup.png")" alt="Thumbs Up" width="30" height="30" />
                @Html.DisplayFor(modelItem => item.VolunteerUpVotes)
            </td>
            <td>
                <img src="@Url.Content("~/Images/thumbsdown.png")" alt="Thumbs Down" width="30" height="30" />
                @Html.DisplayFor(modelItem => item.VolunteerDownVotes)
            </td>
            <td>
                <img src="@Url.Content("~/Images/noshow.jpg")" alt="No Show" width="30" height="30" />
                @Html.DisplayFor(modelItem => item.NoShowCount)
            </td>
            @*
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID })
                </td>*@            
        </tr>
    }

    <tr>
        <td>
            @Html.ActionLink("Back", "Index", "VolunteerEvents")
        </td>
    </tr>

</table>

